### ISSUE TITLE
Upgrading to Kirby 3: Notes regarding using PHP’s count() function vs Kirby’s size() helper

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#100]
Thought I’d add some notes regarding the issues I’ve seen in upgrading a site to v3, that might be useful additions to [the upgrade docs](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2).

### Notes
Perhaps an effect of moving to PHP 7, in most cases you will want to replace PHP’s [`count()`](https://secure.php.net/manual/en/function.count.php) function with Kirby’s own `size()` helper, i.e.:

```diff
-   if (count($page->featured())) {
+   if (size($page->featured())) {
        snippet('mysnippet');
    }
```

**Comment by paulrobertlloyd** [comment]
Yup, `$page->featured()` is a field, like so:

```
title: England
----
feature:
- england/sussex/brighton
- england/surrey/crystal-palace
- england/gloucestershire/bristol
- england/oxfordshire/oxford
- england/devonshire/exeter
- england/cornwall/penzance
```

If I use `$page->featured()->isNotEmpty()` I get the error `Call to a member function isNotEmpty() on array`. Maybe I should be using a different means of checking if a field like this has a value?

**Comment by texnixe** [comment]
You could use `$page->featured()->toPages()->count()`

**Comment by paulrobertlloyd** [comment]
@texnixe Doing that returns `Call to a member function toPages() on array`.

**Comment by texnixe** [comment]
Hm, that should actually work and does in my test.

**Comment by paulrobertlloyd** [comment]
Oops… coming back to this project after a year-long break, so having to get myself familiar again with everything. You’re right @texnixe, this wasn’t querying the field directly, but a value returned by the page model:

```
class RegionPage extends Kirby\Cms\Page
{
    public function featured()
    {
        if ($this->parent() == 'places') { // Page is a country
            $featured = $this->feature()->yaml();

            array_walk($featured, function (&$value, $key) {
                $value = page('places/'.$value);
            });
        } else { // Page is a county
            $featured = $this->children()->filter(function ($page) {
                return $page->hasImages();
            });
        }

        return $featured;
    }
}
```

I suspect this is all more complicated than it needs to be, but `count()` worked in v2, and `size()` works in v3. 🤷‍♂️

(I should add that I’m using `count()/size()` is a few other places too, and I suspect for similar reasons.)

**Comment by texnixe** [comment]
In any case this is nothing that relates to changes in Kirby. I don't quite understand why you don't store your feature pages with the full uri, then this array_walk stuff wouldn't be necessary and you could return a pages collection from your model.

**Comment by paulrobertlloyd** [comment]
@texnixe Totally understand. I just wanted to note down this change, should it be helpful in any upgrade notes. I can’t be sure, but looking at the PHP website it seems like `count` returning an error when it didn’t before is a PHP7 thing? But, maybe not.

As to my code, I suspect lots of this will change as I move to v3 (and as I review stuff like the above and question my previous decisions!!) I also haven’t been using the panel up to this point, but want to with v3. As the structured field type doesn’t allow bare arrays like I have above – and probably for good reason – the way I query and store different values will likely change as a result.

**Comment by texnixe** [comment]
The structure you use above is exactly the result if you use a pages field. Therefore, once you store the stuff with the full path, you can call the `toPages()` method on it and get a pages collection right away.

**Comment by paulrobertlloyd** [comment]
Oh, well that’s perfect! Thanks again for all your help @texnixe.
