### ISSUE TITLE
Field methods example wrong

### ISSUE THREAD

**Issue by distantnative** [k-next/getkirby.com#111]
https://nnnnext.getkirby.com/docs/cheatsheet/extensions/field-methods

The very last one. Shouldn't it be?

```
return $field;
```

**Comment by texnixe** [comment]
Can be both, can't it, depending on wether or not you want further chaining?

**Comment by distantnative** [comment]
Isn't the current one reaturning a boolean value... like hasQuotes does?

**Comment by texnixe** [comment]
Oh, yes, I didn't look close enough, of course, the return value is even the same as in the example before.

**Comment by texnixe** [comment]
✅

**Comment by distantnative** [comment]
👍
