### ISSUE TITLE
Document different types of blueprint extensions

### ISSUE THREAD

**Issue by lukasbestle** [k-next/getkirby.com#114]
Extending blueprints is currently only documented for sections (see https://nnnnext.getkirby.com/docs/guide/blueprints/sections#extending-sections). I think we should have an example for this in the columns and tabs guide as well. There is currently an info box at the end of those pages, but it isn't really clear what it means to beginners ("what is a predefined section again?").

**Comment by texnixe** [comment]
https://github.com/k-next/getkirby.com/issues/34

**Comment by lukasbestle** [comment]
That idea makes a lot more sense. 👍
I'm closing this.
