### ISSUE TITLE
Error Page from Link: guide/pages/creating-pages-and-drafts

### ISSUE THREAD

**Issue by supersmart-at** [k-next/getkirby.com#115]
<img width="639" alt="bildschirmfoto 2018-12-04 um 14 18 54" src="https://user-images.githubusercontent.com/672579/49444600-eb228880-f7cf-11e8-9c77-d8e8305bc7c0.png">
HREF Links to  https://nnnnext.getkirby.com/docs/panel/blueprints/sections/#tab1

**Comment by texnixe** [comment]
✅
