### ISSUE TITLE
Typos on Creating Pages & Drafts

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#119]
## Creating pages manually in the content folder
https://nnnnext.getkirby.com/docs/guide/pages/creating-pages-and-drafts#creating-pages-manually-in-the-content-folder

In the "simple folder structure" tree example, it says `ontact.txt` instead of more-obvious `contact.txt`.

## Creating Page sections that allow adding pages
https://nnnnext.getkirby.com/docs/guide/pages/creating-pages-and-drafts#creating-page-sections-that-allow-adding-pages

It currently says
> Before a user can add new pages via the Panel, you have to set up a - section of type pages that has either the status draft or the status all.

The hyphen looks like a typo to me.

**Comment by texnixe** [comment]
✅

**Comment by texnixe** [comment]
Thanks for your help!
