### ISSUE TITLE
Incomplete Sample Code on File Meta Data

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#120]
In the [Accessing meta data in templates](
https://nnnnext.getkirby.com/docs/guide/media/file-meta-data#accessing-meta-data-in-templates) section, the sample code does not close the `<?php if ($image = $page->image('lake.jpg')): ?>` with anything.

I think it would be helpful to include a `<?php endif ?>` at the end for completeness.

**Comment by texnixe** [comment]
✅
