### ISSUE TITLE
Typos and Suggestion on "Caching" Page

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#124]
The [Caching](https://nnnnext.getkirby.com/docs/guide/cache) page has a couple typos:
1. The "Using the cache" is an `h1`, but seems like an `h2` makes more sense (so it shows up in the TOC)
2. In that section, it says "(for example in a controller" but the parenthesis is never closed.
3. I would use "Set up" (verb) instead of "Setup" (noun) in the "Setup your own cache" heading.

I would also suggest a note added to make it clear where file-based cache is located. It's mentioned in the "Setup your own cache" section, but that specifically concerns itself with an API cache. It's easy enough to guess that what the pages cache location would be, but I think it'd be worth explicitly pointing out.

**Comment by texnixe** [comment]
✅
