### ISSUE TITLE
Typos on "Supporting RTL languages" Page

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#126]
There's a few typos on the [Supporting RTL languages](https://nnnnext.getkirby.com/docs/guide/multi-language/supporting-RTL-languages) page:

1. ``right-to-left (`rtl)`` is missing the final backtick.
2. "Setup language" should be "Set up language"
3. Within the "Setup language" section, there's no space after "direction" in "To do so, add an `direction`entry to your language array"
4. In the "Modify your CSS" section
   1. There's no space after "`rtl`" in "element when the `rtl`class is applied"
   2. There's no space after "`body.rtl`" in "from right to left, when `body.rtl`is applied"

**Comment by texnixe** [comment]
✅
