### ISSUE TITLE
Broken Links on "How to upgrade from Kirby 2"

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#128]
In the [Panel Section](
https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2#panel) of the "How to upgrade from Kirby 2" page, there a couple broken links:

### Remove subpage and file settings from blueprints
- Pages sections
- Files sections

Both go to nonexistent pages

**Comment by neildaniels** [comment]
While not "broken", the link in the "Sort numbering of subpages" section goes to a nonexistent anchor.

> Details: [General blueprint options](
https://nnnnext.getkirby.com/docs/guide/blueprints#general-blueprint-options)

**Comment by neildaniels** [comment]
The hook link in "Remove blueprint-based subpage builder" is broken.
> The option to auto-create subpages via a blueprint setting no longer exists. You can use a [panel.page.create:after hook](
https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-types/hooks) to achieve the same instead.

**Comment by neildaniels** [comment]
The link in "Kirbytext pre/post filters" is broken.
> [Kirbytext pre/post filters](
https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-types/kirbytags#kirbytag-hooks) now have to be registered as hooks.

**Comment by neildaniels** [comment]
The link in "Kirbytags" is broken
> [Kirbytags](https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-types/kirbytags) are now defined in a plugin file.

**Comment by texnixe** [comment]
✅
