### ISSUE TITLE
$user-avatar() Documentation Refers to Outdated Avatar File Location

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#129]
The current docs for [$user->avatar](https://nnnnext.getkirby.com/docs/cheatsheet/user/avatar) says:
> All avatars must go into `/assets/avatars`.

But the [Upgrade from Kirby 2 doc](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2) advises removing this folder:
> Please delete your `accounts` and `assets/avatars` folder and install accounts from scratch for now.

**Comment by texnixe** [comment]
✅
