### ISSUE TITLE
Extensions -> Collections Cheatsheet Page Has Broken Link and Deprecated Code

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#131]
The [Extensions Collections](https://nnnnext.getkirby.com/docs/cheatsheet/extensions/collections) cheatsheet page should have 2 corrections:

The sample code includes:
```
return $site->find('projects')->children()->visible();
```
but that should be `->listed()` instead of `->visible()`

Then, there's a broken link in:
> The required file would be a [collection](
https://nnnnext.getkirby.com/docs/templates/collection) with a return function.

**Comment by texnixe** [comment]
✅
