### ISSUE TITLE
Ensure consistent wording

### ISSUE THREAD

**Issue by lukasbestle** [k-next/getkirby.com#151]
E.g. "Panel" always uppercase.

**Comment by distantnative** [comment]
And I just changed it in a few places to lowercase 🙈
Do we have a style guide for these and other terms?

**Comment by lukasbestle** [comment]
I don't think so, but maybe we should make one.

I'd suggest to use uppercase `Panel` as it's *the* Panel, not some kind of panel. Which other fixed terms do we have besides the Panel?

**Comment by distantnative** [comment]
KirbyTag/s (which I have seen today in all possible forms of capitalization)

**Comment by lukasbestle** [comment]
Maybe we should uppercase everything that's in the [glossary](https://nnnnext.getkirby.com/docs/glossary). So for example also `Blueprint` or `Field Method`. Then it's clear that those terms are fixed and mean exactly that one thing.

On the other hand, that would look a bit strange. So a compromise would be the following:

- Everything that is a "name" of some sorts is uppercased as one word (no camelCase):
  > Kirby, Panel, Kirbytag, Kirbytags, Kirbytext, Smartypants, Markdown, Vue, Whoops
- Abbreviations are full-caps:
  > API
- Everything that is not a "name" or abbreviation is lowercased (if not at the beginning of a sentence):
  > template, snippet, blueprint, field method, ...

I think that's what I would prefer. What do you think @bastianallgeier?

**Comment by distantnative** [comment]
I like that. I'd add that we consistently use `Vue` not `Vue.js`.

**Comment by lukasbestle** [comment]
Hm, in the code we currently use camelCase for `KirbyTag` and `KirbyTags`. So we should probably use that on the site as well. Or change it in the code? I'm not sure.

**Comment by distantnative** [comment]
I don't mind either, but if it is `KirbyTags` it should also be `KirbyText`, right?

**Comment by lukasbestle** [comment]
> Another one I found: Is it GitHub or Github for us?

GitHub, as it's a trademark. We should write those exactly like they are defined.

You are right: The author of SmartyPants also uses camelCase, so that's what we should do as well. But not because we will consistently use camelCase, but just because that's the "right" capitalization. For example Markdown is written without camelCase.

> And... SQL or sql?

SQL, it follows the "it's an acronym" rule.

**Comment by texnixe** [comment]
- SQL, MySQL

**Comment by bastianallgeier** [comment]
I agree with everything said so far. I'm not particularly happy with camelCase myself, but I still think we should use KirbyTags and KirbyText in camelCase. Just because those two are very close and it feels more readable to me in camelCase. 

Do we have any other pseudo-brands? 

Kirby
Panel
KirbyTag
KirbyTags
KirbyText

I can't think of any at the moment.

**Comment by distantnative** [comment]
I'll update the PR with these.
