### ISSUE TITLE
Extensions/Fields: Computed values

### ISSUE THREAD

**Issue by pju-** [k-next/getkirby.com#168]
https://nnnnext.getkirby.com/docs/reference/extensions/fields

In the section on computed values, I think that 'sentence' should be assigned a closure:

```
'computed' => [
    'sentence' => function() {
        $page = kirby()->page('home');
        return $page->title() . ': ' . $page->description();
    }
]
```

Also I found it a bit confusing that I still need to add these values in the vue props: because of the name I thought that they would automatically be passed as computed values.
This wouldn't make much sense I guess, but maybe it could still be mentioned in the docs?

**Comment by distantnative** [comment]
✅
