### ISSUE TITLE
Reference: (link: …) KirbyTag Docs Are Outdated

### ISSUE THREAD

**Issue by neildaniels** [k-next/getkirby.com#174]
The docs for [(link: …)](https://nnnnext.getkirby.com/docs/reference/kirbytags/link) appear to be outdated.

> `(link: http://wikipedia.org text: Wikipedia popup: yes)`

As decided in https://github.com/k-next/kirby/issues/1323, Kirby 3 is not destined to ship with a `popup:` attribute. This sample should be removed.

> `(link: some/page text: Some page in German lang: de)`

I have not actually tested this myself, but looking at the code for the `link:` tag, it seems like the `lang:` has also been removed. If this is in error, a ticket should be filed for that.

**Comment by distantnative** [comment]
I opened an issue for the `lang` attribute to be re-implemented: https://github.com/k-next/kirby/issues/1353

And I will remove the popup example in a second.

✅
