### ISSUE TITLE
Toolkit classes documentation unclear

### ISSUE THREAD

**Issue by texnixe** [k-next/getkirby.com#65]
Something like `$str->slug()` doesn't work and probably shouldn't be documented like this.

**Comment by texnixe** [comment]
These are autogenerated, how can we handle this better?

**Comment by bastianallgeier** [comment]
✅ I worked on improving the display of static vs. non-static methods. I think it's already a lot clearer. I will add more enhancements to the stuff that comes from the reflection over time.
