### ISSUE TITLE
Short intro sections for classes in cheatsheet

### ISSUE THREAD

**Issue by texnixe** [k-next/getkirby.com#66]

**Comment by texnixe** [comment]
I have started adding short descriptions, currently only a test with the first 3 section in the cheatsheet.

@bastianallgeier Let me know what you think, if you are d'accord, I'll continue with the rest.

**Comment by bastianallgeier** [comment]
@texnixe which one did you write so far?

**Comment by bastianallgeier** [comment]
The introductions right now are all from the reflection and they are often too technical. It would be great to have human intros for every class.

**Comment by texnixe** [comment]
I had only started with 3 because I was waiting for your feedback and didn't want to do them all just to delete them afterwards. According to the commit:
- field methods
- fields
- file class

I could complete them tomorrow, if you'd rather do something else.

**Comment by bastianallgeier** [comment]
That would be great! I will work on various parts of the docs today, but I didn't plan to work on the descriptions. I think eventually it would be even cooler if we could add small docs and code examples to each overview page in the cheatsheet. For example it would make a lot of sense in my opinion to explain on the field methods page, how you use them in a template. Not a huge article, but a short intro. 

Another good example is the $request class. It's super hard to understand right now how you would get to the request class at all. If we have a small code example at the top and a bit more text around it with some basic tipps, the method reference would instantly become a lot more helpful after reading that.

**Comment by texnixe** [comment]
Yes, with the new structure of the Cheat Sheet this is now possible.

**Comment by bastianallgeier** [comment]
I don't know how you think about it, but I see the cheatsheet more and more as our "source of truth" and a very detailed reference. The more we add details there, the more we can shorten the guide and trim it down to an essential introduction to each topic. I think this could really solve the problem in the end that we often don't know where we should place certain docs. 

I have this idea in mind that we could build a quick look feature for the cheatsheet that can be included in every guide page. Something like `(cheatsheet: options/api)` could then include a simple text link that is enhanced with JS to open the cheatsheet article as overlay directly after clicking on that link. From there you could easily close the overlay again to return to the guide or maybe even navigate through the cheatsheet in the overlay. We would need to test if that would be overkill though.

**Comment by texnixe** [comment]
I'd prefer that as well. Then the guide would me more conceptual and the examples would be in the Cheat Sheet. This would really solve quite a few problems also with maintaining the docs.

This concept would then be extended with the cookbook recipes that contains recipes for specific use cases, quicksteps and the more conceptual `how-tos`suggested by Sylvain.

**Comment by bastianallgeier** [comment]
💯 Exactly!!
