### ISSUE TITLE
Document $kirby methods in the cheat sheet

### ISSUE THREAD

**Issue by sylvainjule** [k-next/getkirby.com#73]
You've already mentioned [$kirby->page()](https://github.com/k-next/getkirby.com/issues/56), but there seems to be some other methods attached to `$kirby` that could be quite useful, like:

`$kirby->multilang()`
`$kirby->languages()`
etc.

**Comment by texnixe** [comment]
Yes, they are actually documented, but we have hidden the framework documentation to not overwhelm users: https://nnnnext.getkirby.com/docs/framework/cms/app

However, I think we should probably move some parts into the cheatsheet.

**Comment by sylvainjule** [comment]
Thanks! I found the page, but I also thought that some of them could be good candidates for the cheasheet, mostly the ones dealing with languages.

The framework docs is missing the `->defaultLanguage()` method :)

**Comment by bastianallgeier** [comment]
✅
