### ISSUE TITLE
[Docs] Document or change `date()` vs `toDate()`methods

### ISSUE THREAD

**Issue by johannahoerrmann** [k-next/getkirby.com#80]
https://nnnnext.getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display-in-the-info-option-of-an-item

On this page, I did not understand that this example `info: {{ page.from.toDate('d.m.Y') }}` would not work if the date field is actually called `date`.

So this wouldn't work: `info: {{ page.date.toDate('d.m.Y') }}`
But this does: `info: {{ page.date('d.m.Y') }}`

**Comment by nilshoerrmann** [comment]
@texnixe [explained on Slack](https://getkirby.slack.com/archives/CBN859614/p1541501055338800) that a date field named "date" is a special use case that is automatically converted to a date. 

There is certainly a convincing internal logic for this but from the outside this is not comprehensible 😬

**Comment by texnixe** [comment]
@bastian What is the current status regarding this issue? Doesn't seem to be resolved yet although we all agreed to change this?

**Comment by bastianallgeier** [comment]
Hihi, you mentioned the wrong @bastian Poor guy :) 

I created a ticket for it: https://github.com/k-next/kirby/issues/1249
