### ISSUE TITLE
[Docs] Numbered h2 (following numbers displayed in table of contents)

### ISSUE THREAD

**Issue by johannahoerrmann** [k-next/getkirby.com#81]
After clicking a link in the table of contents of a doc. page, I got mixed up with what example was relevant – a number prefix for the h2 to match the number displayed in the table of content would have helped me to quickly find the correct spot.

Example: https://nnnnext.getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display-in-the-info-option-of-an-item

**Comment by bastianallgeier** [comment]
✅
