### ISSUE TITLE
[Docs] Fix changeTemplate value

### ISSUE THREAD

**Issue by medienbaecker** [k-next/getkirby.com#86]
Since Beta 6 you have to define the templates that should be available:

```
title: Template Demo
options: 
  template: 
    - article
    - something-else
```

That's not correctly documented in the docs: https://nnnnext.getkirby.com/docs/guide/blueprints#general-blueprint-options (scroll down to options)

Setting `value` to `true` (like suggested) will result in a fatal error in the panel: `Unexpected token < in JSON at position 0`.

While I personally think it would be better in the long run to add the possibility of a `true` option which lists all templates, for now I think changing it in the docs would definitely save a lot of people some time.

**Comment by texnixe** [comment]
The content has been moved and I can't find this template option anywhere, tbh.

**Comment by medienbaecker** [comment]
I found it here: https://nnnnext.getkirby.com/docs/cheatsheet/blueprints/page (scroll down all the way to the bottom)

**Comment by texnixe** [comment]
✅
