### ISSUE TITLE
[UI] Color for selected text not optimal on dark backgrounds

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/getkirby.com#91]
![01](https://user-images.githubusercontent.com/10027897/49093513-8661ae00-f264-11e8-9b31-a4799e26ec5e.png)
![02](https://user-images.githubusercontent.com/10027897/49093510-85308100-f264-11e8-9b44-3a2ca65da8a5.png)

**Comment by bastianallgeier** [comment]
✅
