### ISSUE TITLE
Link to configuration options from Configuration page in main docs

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#92]
The documentation on [the Configuration page](https://nnnnext.getkirby.com/docs/guide/configuration) provides information and links about available roots, urls and panel configuration options, but there is no information provided about the general configuration options available (e.g. `url`, `cache` etc.). These are actually [available in the cheet sheet](https://nnnnext.getkirby.com/docs/cheatsheet/options), so perhaps a prominent link should be provided to them from this page.

**Comment by bastianallgeier** [comment]
✅
