### ISSUE TITLE
[Docs] Include information about passing HTML to $content in Html::tag

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#94]
Trying to pass a string of HTML into the `$content` of `Html::tag` without it being encoded, I encountered the following:

```php
echo $title; // => <a href="#">Text</a>
echo Html::tag('h1', $title); // => <h1>&lt;a href=&quot;#&quot;&gt;Text&lt;/a&gt;</h1>
```
Tried using `HTML::encode` and `HTML::decode` in various combinations, but no luck! Turns out, thanks to @bastianallgeier’s help on Slack, that you actually need to pass `$title` as an array, like so:

```php
echo Html::tag('h1', [$title]); // => <h1><a href="#">Text</a></h1>
```

This isn’t an obvious solution, and certainly not clear from the documentation (where it only says that `$content` is `mixed`). Can more detail about this particular use case be added to the docs?

**Comment by texnixe** [comment]
✅
