### ISSUE TITLE
Upgrading to Kirby 3: Notes regarding custom KirbyTags

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#95]
Thought I’d add some notes regarding the issues I’ve seen in upgrading a site to v3, that might be useful additions to [the upgrade docs](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2).

### Notes
For the custom tag `(foo: value1 bar: value2)`:

`$tag->attr('foo')` becomes `$tag->value()`
`$tag->attr('bar')` becomes `$tag->bar()`

### Findings
This new format means you can no longer specify a fallback value, as you could previously:

`$tag->attr('bar', 'fallback')`

Also, if a tag allows for multiple attributes, you can no longer leave the first blank. So whereas `(foo: bar: value2)` previously worked, it won’t in Kirby 3.

Are these findings correct?

**Comment by bastianallgeier** [comment]
The old syntax with `$tag->attr()` still works and you can still provide fallbacks with this. 

The new tag properties are just a way to write cleaner code without additional function calls. Providing fallbacks with them also still works with PHP 7's great ?? operator

```
return $tag->value ?? 'my fallback if the value is null'
```

But it's perfectly fine to stick to the attr helper.

**Comment by paulrobertlloyd** [comment]
Ah, excellent. I thought I tried using this `$tag->attr()`, but will try again. And now knowing about the great operator will simplify quite a bit of code!

**Comment by paulrobertlloyd** [comment]
Might pay to add this information [to the docs](https://nnnnext.getkirby.com/docs/guide/extending-kirby/plugin-types/kirbytags) – add are these KirbyTag methods documented in the cheat sheet anywhere?
