### ISSUE TITLE
Upgrading to Kirby 3: Notes regarding routes

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#96]
Thought I’d add some notes regarding the issues I’ve seen in upgrading a site to v3, that might be useful additions to [the upgrade docs](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2).

### Notes
If using `tpl::load`, this now needs to be explicitly returned, i.e.:

```diff
'routes' => [[
    'pattern' => 'app.webmanifest',
    'action' => function () {
-       tpl::load(kirby()->roots()->templates().DS.'app.webmanifest.php', [
+       return tpl::load(kirby()->roots()->templates().DS.'app.webmanifest.php', [
            'site' => kirby()->site()
        ]);
    }
]]
```

### Findings
Perhaps this was always the case, and things are a bit stricter now. And maybe this effects other routing methods as well.

**Comment by texnixe** [comment]
I don't think this has anything to do with the `tpl::load()` method, but with the route.

**Comment by texnixe** [comment]
I moved this to the migration issue
