### ISSUE TITLE
Upgrading to Kirby 3: Notes regarding getting pagination items

### ISSUE THREAD

**Issue by paulrobertlloyd** [k-next/getkirby.com#99]
Thought I’d add some notes regarding the issues I’ve seen in upgrading a site to v3, that might be useful additions to [the upgrade docs](https://nnnnext.getkirby.com/docs/guide/installation-and-updates/how-to-upgrade-from-kirby-2).

### Notes
It would seem Kirby has renamed one of the getters on the `$pagination` object. Whereas previously you would need to call `pagination->items()`, you now need to call `pagination->total()`.

**Comment by paulrobertlloyd** [comment]
What was the resolution for this issue, out of interest?

**Comment by texnixe** [comment]
Oops, I had a problem yesterday with the website no longer working locally and completely forgot to commit.
